package com.godsplan.payments.error;

public enum ErrorCode {
    VALIDATION_FAILED, INVALID_AMOUNT, INVALID_CURRENCY, INVALID_ACCOUNT, INSUFFICIENT_FUNDS,
    DUPLICATE_PAYMENT, INVALID_STATUS_TRANSITION, PAYMENT_NOT_FOUND, PROCESSING_ERROR, NETWORK_ERROR,
    CURRENCY_MISMATCH, EXCHANGE_RATE_UNAVAILABLE, STALE_EXCHANGE_RATE, CONVERSION_LIMIT_EXCEEDED,
    CUSTOMER_NOT_FOUND
}
